### ISSUE TITLE
显存溢出

### ISSUE THREAD

**Issue by CHDQ** [Whu-wxy/Non-local-U-Nets-2D-block#4]
您好，请问您是在什么环境跑的  是gpu集群还是单gpu，用图片作为输入的时候，显存直接就溢出了
下面是我用于测试的代码，是否存在问题，麻烦指正一下，谢谢
```
    device = torch.device('cuda')  # cuda:0
    inputs = torch.rand(1, 3, 360, 480).to(device)
    net = multi_head_attention_2d(
        3, 4, 4, 4, 2, 0.5, 'DOWN').to(device)   # 'SAME', 'DOWN', 'UP'
    res = net(inputs)
    print('res shape:', res.shape)
```

```
Traceback (most recent call last):
  File "multi_head_attention_2d.py", line 129, in <module>
    res = net(inputs)
  File "D:\ProgramData\Anaconda3\envs\torch_last\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "multi_head_attention_2d.py", line 94, in forward
    A = torch.matmul(q, k.transpose(0, 1))
RuntimeError: CUDA out of memory. Tried to allocate 111.24 GiB (GPU 0; 6.00 GiB total capacity; 7.91 MiB already allocated; 4.32 GiB free; 22.00 MiB reserved in total by PyTorch)
```

**Comment by Whu-wxy** [comment]
测试用的cpu。attention不会用在输入部分直接处理图像的，在网络高层，图像变小。你再试试，我当时测试是(20, 50, 50)的图

**Comment by CHDQ** [comment]
> 测试用的cpu。attention不会用在输入部分直接处理图像的，在网络高层，图像变小。你再试试，我当时测试是(20, 50, 50)的图

感谢回复。(20, 50, 50)尺寸的图像大小是可以正常运行的，图像尺寸比较大的时候，超过200*200好像就不行了，有什么解决建议么

**Comment by Whu-wxy** [comment]
建议下采样一下哦亲

**Comment by CHDQ** [comment]
```
net = multi_head_attention_2d(
        3, 4, 4, 4, 2, 0.5, 'DOWN').to(device)   # 'SAME', 'DOWN', 'UP'
```
您的这段代码不就是下采样么

**Comment by Whu-wxy** [comment]
输入feature还是有点大

**Comment by CHDQ** [comment]
> 输入feature还是有点大

好的，谢谢
